version: "3"
services:
  datascience-notebook:
      build: .
      environment:
        - JUPYTER_TOKEN=123456
      volumes:
        - ./src:/home/jovyan
        - /Users/80448/kongdev/excel_content:/home/jovyan/excel_content
        - /Users/80448/kongdev/excel_share:/home/jovyan/excel_share
      ports:
        - 8888:8888
      container_name: py-container
      command: jupyter notebook --NotebookApp.iopub_data_rate_limit=10e10